language: python

python:
  - 3.4
  - 3.5
  - 3.6
  - 3.7

env:
  - DJANGO=1.8

install:
  - pip install -r requirements.txt
  - pip install -q Django==$DJANGO
  - pip install coveralls

script:
  - python manage.py test

after_success:
  - coveralls
