language: python

python:
    - 3.2
    - 3.3
    - 3.4

env:
    - DJANGO=1.6
    - DJANGO=1.7

install:
    - pip install --use-mirrors -r requirements.txt
    - pip install -q Django==$DJANGO --use-mirrors
    - pip install coveralls

script:
    - nosetests --with-coverage --cover-package=twingo2

after_success:
    - coveralls
